### ISSUE TITLE
Install-ContainerHost.ps1 on TP5: Error checking context: 'can't stat '\\?\C:\Windows\System32\LogFiles\WMI\RtBackup''.

### ISSUE THREAD

**Issue by mathiasconradt** [MicrosoftDocs/Virtualization-Documentation#232] opened 2016-05-03 13:21 UTC
Setting up a new Windows Server 2016 TP5 as a container host by running this:

```
wget -uri https://aka.ms/tp5/Install-ContainerHost -OutFile c:\Install-ContainerHost.ps1
powershell.exe -NoProfile -ExecutionPolicy Bypass C:\Install-ContainerHost.ps1
```

as per https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_configure_host#scripted-existing-system-1-

I am getting:

`Error checking context: 'can't stat '\\?\C:\Windows\System32\LogFiles\WMI\RtBackup''.`

somewhere near the end (after the setup script restarted the system and continued with the setup) and the `C:\Install-ContainerHost.err` remained on the system.

Running c:\Install-ContainerHost.ps1 a **second time** shows:

```
PS C:\> .\Install-ContainerHost.ps1
Querying status of Windows feature: Containers...
Feature Containers is already enabled.
Configuring ICMP firewall rules for containers...
Docker is already installed.
Image WindowsServerCore is already installed on this machine.
Script complete!
```

and no remaining `C:\Install-ContainerHost.err`.

Afterwards I can run "Get-ContainerImage" and it works fine. (However there is an issue with using the Docker command to build an image based on windowsservercore, but I will create a separate ticket for that.)

**Comment by mathiasconradt** [comment] 2016-05-19 09:15
I setup a new TP5 machine and ran the script again, the same error occurs. Does not seem to have been a one-time temporary issue.
Screenshot: https://snag.gy/uEQ5ce.jpg

**Comment by mathiasconradt** [comment] 2016-05-23 08:12
Today I setup a new TP5 on Azure. Same error

`Error checking context: 'can't stat '\\?\C:\Windows\System32\LogFiles\WMI\RtBackup''.`

as above occurs during the InstallContainerHost.ps1.

**Comment by PatrickLang** [comment] 2016-05-25 06:37
@mebersol are you aware of this? I just confirmed it as well in the latest script.

```
Querying status of Windows feature: Containers...
Feature Containers is already enabled.
SUCCESS: The scheduled task "ContainerBootstrap" was successfully deleted.
Configuring ICMP firewall rules for containers...
Installing Docker...
Installing Docker daemon...
Creating Docker program data...
This script uses a third party tool: NSSM. For more information, see https://nssm.cc/usage
Downloading NSSM...
Extracting NSSM from archive...
Configuring NSSM for Docker service...
Starting Docker...
Waiting for Docker daemon...
Successfully connected to Docker Daemon.
The following images are present on this machine:
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE

Installing ContainerImage provider...
Getting Container OS image (WindowsServerCore -MinimumVersion 10.0.14300.1000 -MaximumVersion 10.0.14300.1010) from OneGet (this may take a few minutes)...
WARNING: Based on customer feedback, we are updating the Containers PowerShell module to better align with Docker. As
part of that some cmdlet and parameter names may change in future releases. To learn more about these changes as well
as to join in the design process or provide usage feedback please refer to http://aka.ms/windowscontainers/powershell
Container base image install complete.
Creating a first boot layer...
Error checking context: 'can't stat '\\?\C:\Windows\System32\LogFiles\WMI\RtBackup''.
Script complete!
```

**Comment by tiagomacarios** [comment] 2016-06-04 02:05
Just installed TP5 and had exactly the same issue.

Followed these instructions: https://blogs.msdn.microsoft.com/jcorioland/2016/04/28/getting-started-with-containers-and-docker-on-windows-server-2016-technical-preview-5/

**Comment by enderb-ms** [comment] 2017-11-15 21:48
Closing this issue since we no longer support this installer script. Please see [this guide](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server) for the new way of setting up containers.

**Closed by enderb-ms** 2017-11-15 21:48 UTC
Labels: Windows Containers
