### ISSUE TITLE
Docker pull fails

### ISSUE THREAD

**Issue by JanneRantala** [MicrosoftDocs/Virtualization-Documentation#530] opened 2017-01-10 07:23 UTC
Hi,

I've faced an issue when trying to build or pull images since last week. I was on a holiday for couple of weeks and before I left, everything was working just fine. But now, I can't pull base images anymore or create new images. 

When pulling for example microsoft/nanoserver, I'm getting this error
`$ docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Extracting [==================================================>] 252.7 MB/252.7 MB
10bf725c5388: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage D:\docker\windowsfilter\416f5b183bda6515686496e4cc53d4a1f1e0ccf0a5fc70e1bbfb95a50081d86e\UtilityVM: winapi error #3489661090`

I tried clearing whole Docker installation along with c:\ProgramData\Docker -folder, moved everything to D-drive but still getting the same error. 
I'm currently using this version:

Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   e8e4546
 Built:        Mon Jan  9 12:27:46 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.4
 Git commit:   e8e4546
 Built:        Mon Jan  9 12:27:46 2017
 OS/Arch:      windows/amd64
 Experimental: false

But same happened with version 1.13.0-rc4. I'm using Windows 10 Anniversary Edition with all latest updates installed. It's really frustrating that problems with Windows Containers and/or Docker just suddenly appear without any notice. Now I'm not sure if this is Docker or Windows platform issue but nevertheless, we're really trying to start using this in our daily development and having show stoppers like these doesn't really give any confidence doing that.

Regards,

Janne

**Comment by JanneRantala** [comment] 2017-01-21 15:52
My setup is Dell XPS 15, 1TB NVMe SSD, TPM enabled, running Windows 10 Anniversary Edition with latest updates. McAfee Agent version 5.0.3.316, McAfee VirusScan Enterprise + AntiSpyware Enterprise version 8.8.0 (8.8.0.1445). Is there anything else I should check, @StefanScherer?

**Comment by StefanScherer** [comment] 2017-01-22 16:26
Thanks @JanneRantala. Enough information right now for me. I'll try to get a Win10 machine next week, I think we also have McAfee at work.

**Comment by friism** [comment] 2017-01-22 16:54
@JanneRantala Did you try disabling McAfee - many people are reporting problems with anti-virus software.

**Comment by JanneRantala** [comment] 2017-01-22 17:33
@friism That's the problem, I can't disable that because of a corporate policy. Even if I could, is that really a proper solution for this? I mean even if it would help, people can't just go and disable their antivirus for good to get Docker working? And does it still doesn't explain why it was working fine for couple of months? I really don't know, that's why I'm asking.

**Comment by JanneRantala** [comment] 2017-01-22 17:38
@friism Would it help if I try to get Docker's folder excluded in McAfee's scans?

**Comment by StefanScherer** [comment] 2017-01-22 18:00
That might help. If you can try this would be good.

**Comment by JanneRantala** [comment] 2017-01-22 18:13
@StefanScherer I can always ask if security department is willing do that :) Also noticed that there's newer version of McAfee's VSE which is supposed to support Windows 10's Anniversary Edition. I'm trying to get that updated too. Hopefully one of those helps.

**Comment by JanneRantala** [comment] 2017-01-23 11:17
@StefanScherer @friism Before installing version of McAfee which supports Windows 10 Anniversary edition I uninstalled McAfee completely. So I didn't have either McAfee Agent or VirusScan Enterprise installed on my laptop but I still got that Docker error message. And needless to say, the same error appeared also after McAfee was updated. So at least in my case it doesn't seem to be McAfee's fault?

**Comment by JanneRantala** [comment] 2017-02-02 08:36
I'm still waiting for comments on this. I've said that I'm willing to do/test anything that I can to help fixing this issue and that still stands. Isn't there really no one else who's having this problem besides me or isn't anyone interested in this?

**Comment by JanneRantala** [comment] 2017-02-28 13:53
Hi @PatrickLang, this is the bug I was referring to few days ago. I'm having the same issue with two identical Dell XPS 15's. It would be great if you could provide me a link to open a support ticket to get this solved. Thanks.

**Comment by PatrickLang** [comment] 2017-02-28 17:32
Home: https://support.microsoft.com/en-us/contactus/
Business: https://support.microsoft.com/en-us/gp/contactus81?Audience=Commercial

I'm still trying to see if I can get a better contact on this.

It's also worth updating your Docker version to v1.13.1 just to see if that changes anything. There were a few occasional issues with `docker pull` fixed during v1.13 development

**Comment by JanneRantala** [comment] 2017-02-28 18:00
@PatrickLang Installed Docker 1.13.1 today and got the same error.

**Comment by JanneRantala** [comment] 2017-03-01 21:16
Solution suggested by @johnvanloon and @jhiller for docker load issue [https://github.com/Microsoft/Virtualization-Documentation/issues/355](https://github.com/Microsoft/Virtualization-Documentation/issues/355) fixed also issue with docker pull. 

> If you have local admin rights, running this reg script will allow you to pull images if you have the "Deny write access to fixed not protected by Bitlocker" group policy enabled.

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Policies\Microsoft\FVE]
"FDVDenyWriteAccess"=dword:00000000

Ping @PatrickLang

**Comment by JanneRantala** [comment] 2017-03-03 13:25
It seems that group policy has enabled that registry value again. Something else needs to be done to get this fixed so that we don't need to go and edit registry every day.

**Comment by mylesbkeating1993** [comment] 2017-04-06 15:12
Hi Janne,

Are you still having issues?

**Comment by JanneRantala** [comment] 2017-04-06 15:50
Hi,

Yeah, unfortunately I do. Like @PatrickLang wrote in issue #355, this Bitlocker problem has to be fixed by Windows devs. I don't know has that thing progressed yet, at least I'm still having this same problem.

**Comment by mylesbkeating1993** [comment] 2017-04-07 19:47
Oh man, I just read through 355, that's a big one.

I know this must be frustrating, thanks for your patience.  

It seems like in your case there is a corporate GPO policy with bitlocker preventing access to the VHD until it is scanned, which breaks pulling new images?  And your workplace can't make an exception to the policy?

But then it sounds like you have a PS script you are running manually to change the registry key as a workaround?  Does this workaround work, although it's not ideal?

Do I have that all correct?  Or are there new developments?

As @PatrickLang said, the best option really is the forums to get support.
1. Microsoft Containers forum: https://social.msdn.microsoft.com/Forums/en-US/home?category=virtualization&filter=alltypes&brandIgnore=True&sort=relevancedesc&filter=alltypes&searchTerm=

2. Docker forum:  www.forums.docker.com

We really do take feedback seriously.  We're Program Managers, and it's our goal to seek customer feedback and use it to direct software development.  

Thank you for helping us make containers better!

**Comment by jhiller** [comment] 2017-04-07 20:18
I think that sums it up nicely.  The workaround does work as long as you have administrator rights (or rights to change the registry).

**Comment by JanneRantala** [comment] 2017-04-07 20:39
It works for me as well but definitely not an ideal solution. I'm really
waiting for that Windows fix which Patrick mentioned. Speaking of that,
would it be possible to update status on that fix maybe to this thread? I'd
be very happy to know if it's in progress or not, or when we might expect
it to be published. Thanks.
pe 7. huhtikuuta 2017 klo 23.18 jhiller <notifications@github.com>
kirjoitti:

**Comment by PatrickLang** [comment] 2017-04-07 20:52
I know this is frustrating but I can't say if/when a fix will be issued. Based on history, any Windows change takes multiple months or longer to deliver, and not every issue reported is fixed. I think automating the workaround to change the FVE.. regkey is the best option available if you cannot get the policy changed in the domain.

**Comment by JanneRantala** [comment] 2017-04-07 21:05
I hope you're not trying to hint that this issue might never be fixed :)
pe 7. huhtikuuta 2017 klo 23.52 Patrick Lang <notifications@github.com>
kirjoitti:

**Comment by mylesbkeating1993** [comment] 2017-04-10 19:24
@JanneRantala 
Patrick is saying we have more work we want to do than we can do.  Such is life.

We measure the impact of product issues based on a mix of:
1. [Uservoice](https://windowsserver.uservoice.com/forums/295050-virtualization)
2. Common issues on the [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/home?forum=windowscontainers) and the [Docker forum](https://forums.docker.com/)
3. Conversations like this one with customers like you

Posting the suggestion in UserVoice and getting colleagues to vote the issue up (if they also have the problem) will directly improve the chances of us working on this issue.

We will absolutely take this conversation with you into consideration.  That does not guarantee that fixing the issue is more important than the many other customer issues and conversations and our broader strategic goals.

It's a tough balance.  We are trying our best. 

If you feel like we're not prioritizing important things, please let us know any time :)

Does that make sense?

**Comment by JanneRantala** [comment] 2017-04-10 20:49
Well first of all I think you misinterpreted my message, I wasn't saying
that you should put this to your list with highest priority nor did I
suggest that you're not doing your job.

My point was that I'm only hoping that this issue gets fixed one day. I
might be the lucky one since I can turn this off just by changing registry
but I believe there are those who can not do that. For them, this is a show
stopper.

What I understood from Patrick's message that not all reported issues will
be fixed. For that, was my clearly failed attempt to lighten the mood.

I've also opened issue in Uservoice and discussed about it in MSDN Forums
which, in my opinion, are not the best place to look for answers because
the lack of replies.
ma 10. huhtikuuta 2017 klo 22.24 Myles Keating <notifications@github.com>
kirjoitti:

**Comment by mylesbkeating1993** [comment] 2017-04-10 20:58
Haha gotcha :)  I wasn't sure if you were seriously upset and didn't want to make light of things if you were.

I actually linked the wrong uservoice.  Here's the container-specific one:
https://microsoft-my.sharepoint.com/personal/mykeatin_microsoft_com/_layouts/15/onedrive.aspx?d=w98dafec7ce244028a3d2c8766a920d59&cid=

We've realized the forum is not where it needs to be as well.  So, I'm focusing primarily on Container customer support going forward.  There will be responses - just give me some time to get to everything :)

Thanks for caring enough to talk and open the uservoice / forum posts.  It's really much more fun to work on things people care about.

Cheers

**Comment by enderb-ms** [comment] 2017-11-15 22:21
Closing this issue as it seems like you've found a solution in the issue referenced above. We are tracking the bitlocker issue internally. Feel free to open this issue again if there is still something we can help with.

**Closed by enderb-ms** 2017-11-15 22:21 UTC

**Comment by weijuans** [comment] 2018-01-29 19:15
Hello All - wanted to let you know we now have fixed this issue in our recent Server Insider build 17074 and higher. Please do download and give it a try. Let us know if we indeed did the job!

Here you can find the recent Server Core container Insider builds: 
https://hub.docker.com/r/microsoft/windowsservercore-insider/

Here is a blog related to this fix and other ones: 
https://blogs.technet.microsoft.com/virtualization/2018/01/22/a-smaller-windows-server-core-container-with-better-application-compatibility/

**Comment by weijuans-msft** [comment] 2018-02-14 00:58
@JanneRantala @StefanScherer can you help validate if we indeed fixed this issue here? Any Server insider builds 17074 or higher should work. Thanks!

**Comment by StefanScherer** [comment] 2018-02-14 06:30
@weijuans-msft Thanks. I haven't encountered this problem locally in VM's for a long time, both 2016, 1709 or Insider builds.

From time to time I see this happen in my AppVeyor builds, eg. at https://ci.appveyor.com/project/StefanScherer/dockerfiles-windows/build/1.0.1017#L458 - exact OS and Docker version is at the beginning of the log.

**Comment by JanneRantala** [comment] 2018-02-14 18:49
@weijuans-msft Thanks, however my issue is with Windows 10 laptop, any idea when the fix will be available there?

**Comment by weijuans-msft** [comment] 2018-02-14 18:57
@JanneRantala Did you mean you run those Docker commands on Windows containers with Windows 10 laptop? If so, get a recent Windows 10 insider build (17074 or higher) as the host, and a corresponding Windows containers of the same build, and that should work. The failure was on the container initiation part. It's not an Windows 10 issue. But you do need the same (or higher) Windows 10 insider build as the host to run the container with the fix.

**Comment by weijuans-msft** [comment] 2018-02-14 19:02
@StefanScherer the issues from AppVeyor seemed different from what was reported earlier in this thread regarding FDVDenyWriteAccess. Right?

**Comment by JoshSchreuder** [comment] 2018-04-10 12:16
I tried in a fresh Windows 10 Enterprise N 1709 VM and installed McAfee Endpoint Protection 10.5.3.3178.

Out of the box the `docker pull` command worked fine.

Running 10.5.1 elsewhere and it has this issue, not 100% if it's McAfee or some other environmental issue.

**Comment by BatmanAoD** [comment] 2018-06-12 18:31
@JoshSchreuder  Do you have the "Deny write access to fixed not protected by Bitlocker" group policy enabled? That's what causes this issue.

**Comment by JoshSchreuder** [comment] 2018-06-15 00:00
@BatmanAoD I think mine was "Not configured" but after changing it to "Disabled" for Fixed Data Drives and Removable Data Drives, this seems to have fixed my issue!

For those with the problem try it out

* Start -> Run -> gpedit.msc
* Computer Configuration -> Administrative Templates -> Windows Components  -> BitLocker Drive Encryption -> (Fixed | Removable) Data Drives -> Deny write access to fixed not protected by Bitlocker
* Set state to disabled
* Reboot

Thanks @BatmanAoD

**Comment by BatmanAoD** [comment] 2018-06-15 15:47
@JoshSchreuder No problem!

Unfortunately, this is still an issue for corporate Windows users like myself, who have that policy locked down by IT.

**Comment by AaronFriel** [comment] 2018-06-17 19:10
Hi, @weijuans-msft was this fix supposed to make it into Windows 10 1803? I am not able to get Windows containers working on a laptop recently updated to 1803 with this corporate policy. The error I get is the same:

> Warning
> 
> Current operation failed because Windows policy "Deny write access to fixed drives not protected by Bitlocker" is enabled. Please disable it and retry the operation

Should that have been fixed in 1803/17134?

**Comment by artisticcheese** [comment] 2018-06-21 20:48
Mcafee AV does **not** support any container operation. https://kc.mcafee.com/corporate/index?page=content&id=KB90041&actp=null&viewlocale=en_US&showDraft=false&platinum_status=false&locale=en_US

**Comment by JanneRantala** [comment] 2018-06-22 09:50
To be honest, McAfee not supporting containers is quite unbelievable. Microsoft should really do something about that since our voice doesn't seem to have any effect on them.

**Comment by artisticcheese** [comment] 2018-06-22 12:20
Why Microsoft shall do something about  Mcafee not supporting containers? Microsoft product (Windows defender) supports it, Symantec supports it, so obviously issue is with Mcafee not with anything else. Since you are customer of Mcafee and paying them money you have a right to demand from Mcafee to either fix the product or you walk away to vendor who cares about their customer demands.

**Comment by JanneRantala** [comment] 2018-06-22 13:06
Why wouldn't they want to help people using Windows Containers? I work for a company of 70000 people so if I say ditch McAfee, nobody really cares a shit. And McAfee has clearly stated that supporting Containers is not in their plans in the near future. And I'm well aware that the problem is with McAfee and nobody else, you don't have to remind me about that.

**Comment by artisticcheese** [comment] 2018-06-22 13:19
Because Microsoft does not own Mcafee and does not have a say what Mcafee shall support or not. What Microsoft can possibly do other then say use different AV?

**Comment by JanneRantala** [comment] 2018-06-22 16:53
Negotiate for example. Or is that an impossible idea in your opinion?

**Comment by artisticcheese** [comment] 2018-06-22 16:58
Bearing in mind other vendors support containers and Microsoft's own solution (Defender) supports it as well I don't see why would Microsoft plead with third party vendor to support feature of Windows. As per Mcafee `McAfee is investigating these products to make them compatible with Windows containers in the future.` So they are looking for people like you to tell them that you need them to support it. You are customer of Mcafee (through your IT department) so you have full right to escalate to IT and them in return to talk to Mcafee demanding this feature. As an embarrasing example you can show that Symantec announced support for Windows Containers a year ago (https://support.symantec.com/en_US/article.TECH236867.html) and Mcafee announced that they do NOT support only a couple of month ago.

**Comment by weijuans-msft** [comment] 2018-06-22 23:46
Sorry folks that I didn't chime in earlier. The issue was fixed in 1803. Please be sure to get the right build of the host and the container when you validate.

As to AV support on Windows containers, Microsoft has published guidance in the past to AV vendors: 
https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/anti-virus-optimization-for-windows-containers.


Like some of you mentioned, our recommendation is if certain AV doesn't work for you, please do contact the vendor. The vendors are encouraged to contact us if they need help.

**Comment by artisticcheese** [comment] 2018-06-22 23:48
What is `fixed` in 1803? If issue with AV which is incompatible with containers (Mcafee) then how could have it been fixed via Windows OS?

**Comment by weijuans-msft** [comment] 2018-06-22 23:59
The fix is for these issues reported here and User Voice related to BitLocker and FDVDenyWriteAccess policy: Users were not able to run basic Docker commands like Docker Pull.

https://github.com/Microsoft/Virtualization-Documentation/issues/355
https://windowsserver.uservoice.com/forums/304624-containers/suggestions/18544312-fix-docker-load-pull-build-issue-when-bitlocker-is

What we did in the fix was to implement a handshake between VHDMP and BitLocker that provides BitLocker the opportunity to NOT enforce this policy on local loopback mounted VHDs - which is used in container initialization as an intermediate step.

**Comment by AaronFriel** [comment] 2018-06-29 20:18
Hi @weijuans-msft, are you sure this is fixed in 1803?

![image-1](https://user-images.githubusercontent.com/788800/42113037-89ee4186-7baf-11e8-8925-94cb13dd7b94.png)

I don't think it is fixed. Enterprise policy is still preventing Docker for Windows from even using Windows Containers. This is on Windows 10 1803, and this error appears shortly after selecting the Docker context menu option, "Switch to Windows containers..."

**Comment by artisticcheese** [comment] 2018-07-10 20:54
Here is official information from Docker which is AV solutions support windows containers. https://success.docker.com/article/endpoint-security-for-windows-containers

**Comment by tanzislam** [comment] 2018-08-25 13:25
I'm running Windows 10 1803 x64 with Windows Defender enabled, and managed to fix the problem with `docker pull` by excluding `C:\Program Files\Docker\Docker\resources\dockerd.exe` from Controlled Folder Access. (I didn't need to change the BitLocker policy.) My Docker version is 18.06.0-ce.

**Comment by BatmanAoD** [comment] 2018-09-13 22:09
@tanzislam I'm guessing you don't have additional antivirus software installed, and in particular you don't have McAfee?

It seems Controlled Folder Access is automatically disabled when other antivirus providers are enabled, or at least, I don't see any options to configure Controlled Folder Access exceptions.

**Comment by tanzislam** [comment] 2018-09-16 10:01
@BatmanAoD Yes I don't have any other antivirus installed. Looks like Controlled Folder Access [requires the real-time scanning feature of Windows Defender enabled](https://answers.microsoft.com/en-us/protect/forum/protect_defender-protect_updating-windows_10/im-not-able-to-toggle-controlled-folder-access/b6cccab6-6025-4ffb-a7c2-1cbeb190107b?auth=1), which would conflict with 3rd-party antivirus.

I had to configure the exception on Controlled Folder Access by going to Settings -> Update & Security and then clicking the following:
![Switch to the "Windows Security" page and click "Virus & threat protection"](https://user-images.githubusercontent.com/11808226/45595089-30d46f80-b99e-11e8-9ce8-7d2350bfb141.png) ![In the "Virus & threat protection" page of Windows Defender Security Center, scroll down and click "Ransomware protection"](https://user-images.githubusercontent.com/11808226/45595039-4d23dc80-b99d-11e8-9b92-468fc8d92fa1.png) ![Inside the "Ransomware protection" sub-page, click "Allow an app through Controlled Folder Access"](https://user-images.githubusercontent.com/11808226/45595048-6036ac80-b99d-11e8-8759-4d9f00b1a1d6.png)

**Comment by gperrego** [comment] 2018-09-28 16:42
> Sorry folks that I didn't chime in earlier. The issue was fixed in 1803. Please be sure to get the right build of the host and the container when you validate.
> 
> As to AV support on Windows containers, Microsoft has published guidance in the past to AV vendors:
> https://docs.microsoft.com/en-us/windows-hardware/drivers/ifs/anti-virus-optimization-for-windows-containers.
> 
> Like some of you mentioned, our recommendation is if certain AV doesn't work for you, please do contact the vendor. The vendors are encouraged to contact us if they need help.

I've asked this question in the referenced uservoice:

To clarify, which version of Windows 10 (not server) has this been fixed in? Has microsoft supplied a backwards compatible fix for windows 10 1709 or 1703 or is this only fixed in windows 10 1803?

Thanks, 
Greg

**Comment by gperrego** [comment] 2018-10-01 04:29
I think I understand the comment now, she is saying we need to use a container that use the 1803 Server version.  To host an 1803 server version you must have an 1803 Win 10 version.  So the bug fix is in the server version but you can't consume the fix without upgrading win 10 to that version or higher.

There are multiple problems with that for us.

1) Our server host would also need to be 1803 at a minimum to host an 1803 container; which it is not.  This means i can't use this fix unless i upgrade my server host OS to 1803.  It wouldn't matter if i could get my developers to get it working locally if they could never deploy it on the host.

2) My developers Win 10 machines are not using 1803 so they can't consume Server 1803.

So that means I can't have my developers work on their laptops, i would need them to work on an unencrypted (non bitlocker protected) VM.  So now i have to create windows 10 vms that run the most recent support version of win 10 which is 1709 with bitlocker disabled.  This will allow me to host a container locally that will run on the server host.  Now my developers will have to RDP to develop?

We need this fix to be applied to every version of windows server, not just 1803+ or windows containers will be dead on arrival.

Thanks,
Greg

________________________________

**Comment by BatmanAoD** [comment] 2018-12-07 20:44
I'm using 1803, build 17134, and the issue seems to be resolved for me.

(I was previously on build 15xxx where xxx is three digits I don't remember, and I was seeing the BitLocker policy error. I am fairly confident that my BitLocker configuration is unchanged.)

**Comment by gperrego** [comment] 2018-12-07 23:21
Yes 1803 fixes this, but placing the requirement to upgrade to 1803 (windows) is what has stalled my project.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by benzbatman** [comment] 2021-11-26 19:43
> 

@weijuans-msft This user voice (https://windowsserver.uservoice.com/forums/304624-containers/suggestions/18544312-fix-docker-load-pull-build-issue-when-bitlocker-is) - which doesn't seem to be available anymore? - was specifically raised for both Server OS AND Windows 10 OS. However, the fix appears to have only been applied to Server OS builds. This isn't acceptable as most of our users will not be running a Server OS on their workstations.

I have raised another issue for this, and it doesn't appear like we're alone in this!

https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1629
