### ISSUE TITLE
messing up with Windows For Docker vs. manual install

### ISSUE THREAD

**Issue by rs38** [MicrosoftDocs/Virtualization-Documentation#427] opened 2016-10-15 13:56 UTC
that should be clarified somehow and somewhere.
docker was running quite fine with the latest oneget install, but docker-compose was very hard to get it running.
If you try and install **Visual Studio Tools for Docker**, which looks so nice in Mr. Hanselman latest blog, the new problems begin, even if you skip the linux part.
Even without installing Docker for Windows(DfW) you get first into struggle with docker-compose, ending up with labels like  - "com.microsoft.visualstudio.targetoperatingsystem=windows" which seem not to be figured out without that VS plugin.
Installing DfW finally messes things up, especially not being able to create the 2nd pipe with the "_windows" postfix.

If I do not make a big mistake or did not understand quite correct:
this obviously two different (and not co-existing and hard to cross-install) approaches to get in touch with docker should be stressed in the docs.

**Comment by ericwj** [comment] 2016-10-22 11:25
Completely agree. I think there are two separate issues here. I'd like to be able to read about the status of things and understand what is causing those issues. And to have an idea where this is headed and how it might be working when everything is done. Not the details but the goals and perhaps a bit of a timeline.

The first issue being that docker right now seems to require a newer version not supported by DfW to use Windows Containers. Likewise the 1.13.0-dev release does not support Linux or at least you can't get at it on Windows 10.

The second being that there are differences in the tooling and acquisition process between Windows 10 Anniversary Edition and Windows Server. Trying to follow the Quick Start will error saying that it can't do `Enable-WindowsFeature`. However trying to reproduce this having `docker-1.13.0-dev` running, running those commands completely succeed although it probably did little or nothing.

I did find that after installing DfW but stopping the service, it's possible to simply run dockerd from the 1.13.0-dev archive and use nanoserver even while the path is still to the DfW version of docker as evidenced by running `cmd /c where docker`. It might even be possible using some config changes to either and using the `-H <host>` switch to docker, to use both? Haven't tried that though.

It would be really beneficial to have VS use Windows Containers. That saves starting a 2GB VM on a 1.75GB vhdx that needs to be laid out from a 70MB iso file...I'm puzzled as to how those numbers relate. I know it's coming but I would like to be able to understand and read why it doesn't yet. Is it that Nanoserver doesn't run a debugger yet? CorDbg seems to be less than perfect on Windows, but... I haven't really found anywhere to read about these kinds of things.

**Comment by CarmenAPuccio** [comment] 2016-10-31 23:56
@ericwj or @rs38 did either of you manage to get this working? I've been trying to build a solution using 1.12.2-cs2-ws-beta on Windows 2016 with the latest version of Visual Studio Community installed with the Visual Studio Tools for Docker (I don't have access to a Windows 10 box).

If I take any project and add Docker Support I can't get it to build because linux can't be used on this platform (2016). If i change the label to "com.microsoft.visualstudio.targetoperatingsystem=windows" I get the below:

The "PrepareForCompile" task failed unexpectedly. System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary

**Comment by rs38** [comment] 2016-11-02 09:51
I did not try that again with DfW. installing windows-only docker was much more relaible for me

**Comment by PatrickLang** [comment] 2016-11-18 18:56
@enderb-ms can you close this with a link to how to correctly set up DfW & VS?

**Comment by Mookker** [comment] 2017-02-14 13:37
Any updates on this one?
I've got exactly same issue, is there any workaround?

**Comment by enderb-ms** [comment] 2017-11-15 21:17
You can read more about using the Visual Studio Tools for Docker [here.](https://docs.microsoft.com/en-us/dotnet/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker)

**Closed by enderb-ms** 2017-11-15 21:17 UTC
Labels: Windows Containers
